adjective1 = input("Enter an adjective: ")
noun1 = input("Enter a noun: ")
verb1 = input("Enter a verb: ")
adjective2 = input("Enter another adjective: ")
noun2 = input("Enter another noun: ")
verb2 = input("Enter another verb: ")
adjective3 = input("Enter one more adjective: ")
noun3 = input("Enter one more noun: ")
verb3 = input("Enter one more verb: ")
print("YOUR MADLIB")
print(noun1, adjective2, verb3, "over the tree.")
print(noun2, adjective1, verb1, "on the deck.")
print(noun3, adjective3, verb2, "into the sky.")
